// <auto-generated />
namespace Projekat_20_dec_v_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BazaPodataka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BazaPodataka));
        
        string IMigrationMetadata.Id
        {
            get { return "201812201510286_BazaPodataka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
